### ISSUE TITLE
1.0.1 release - error on entering instance

### ISSUE THREAD

**Issue by ceylina** [cogwerkz/NiceBubbles#1]
150x NiceBubbles\NiceBubbles-1.0.lua:76: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
NiceBubbles\NiceBubbles-1.0.lua:76: in function `IsBubble'
NiceBubbles\NiceBubbles-1.0.lua:90: in function <NiceBubbles\NiceBubbles.lua:85>

Locals:
(*temporary) = ForbiddenNamePlate1 {
 0 = <userdata>
}

Does this have to do with friendly nameplates being disabled in 7.2 inside instances?

**Comment by ceylina** [comment]
Also

257x NiceBubbles\NiceBubbles-1.0.lua:77: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetRegions'
NiceBubbles\NiceBubbles-1.0.lua:77: in function `IsBubble'
NiceBubbles\NiceBubbles-1.0.lua:90: in function <NiceBubbles\NiceBubbles.lua:85>

Locals:
(*temporary) = ForbiddenNamePlate1 {
 0 = <userdata>
}

**Comment by goldpaw** [comment]
Either you're not using the most recent version of NiceBubbles, or you're using an older version of the 7.2.0 wow patch. The current version is build 24015, and I set NiceBubbles to look for that when deciding whether or not it should do an extra check for the patch 7.2.0 nameplates, which indeed is the cause of the bug. 

Try typing this in-game: 
/run print(GetBuildInfo())

The output should be something similar to this: 
7.2.0 24015 Apr 27 2017 70200

If the second number is different, let me know what it is, and also what region you're playing in if it's a live Legion realm. I thought all realms were at max build version, but if that's not the case, I'll update the addon ofc. :) 

Oh, and If it is a private 7.2.0 realm let me know that too, so I can make an exception for that in the addon. Though I honestly thought the only private Legion realms all were on 7.1.5 still. :o

**Comment by goldpaw** [comment]
I lowered the wow client build number that identifies patch 7.2.0 from the most recent build 24015 to the first public build 23436. Hopefully this solves the issue for anybody that experienced it.
